//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.camixo.posiljanjeobvestilstoritev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.camixo.posiljanjeobvestilstoritev.shema.RezultatTip;
import com.camixo.posiljanjeobvestilstoritev.shema.SporociloTip;

@WebService(name = "PosiljanjeObvestilStoritev", targetNamespace = "http://www.camixo.com/PosiljanjeObvestilStoritev/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.camixo.posiljanjeobvestilstoritev.ObjectFactory.class,
    com.camixo.posiljanjeobvestilstoritev.shema.ObjectFactory.class
})
public interface PosiljanjeObvestilStoritev {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.camixo.posiljanjeobvestilstoritev.shema.RezultatTip
     */
    @WebMethod(action = "http://www.camixo.com/PosiljanjeObvestilStoritev/posljiSporocilo")
    @WebResult(name = "posljiSporociloResponse", targetNamespace = "http://www.camixo.com/PosiljanjeObvestilStoritev/", partName = "parameters")
    public RezultatTip posljiSporocilo(
        @WebParam(name = "posljiSporocilo", targetNamespace = "http://www.camixo.com/PosiljanjeObvestilStoritev/", partName = "parameters")
        SporociloTip parameters);

}
